# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - i12katongweb-ut

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          NODE_ENV: production
          APP_KEYS: cjyqihun+/0/xdqkw6ucia==,tskat0xkqnomlkqjocx1tq==,3emcmbonepryrvd2s04+g==,9wgb+fwgqlppakb/niogzw==
          API_TOKEN_SALT: 8ldtusiadjhs4zwkks4rlq==
          ADMIN_JWT_SECRET: /getsswdsn7el6ix/c/efa==
          TRANSFER_TOKEN_SALT: ygfjp8xvxoj91+ktp+rwqg==
          
          # Database
          JWT_SECRET: wdhceroaqugvyk8djutcxo==
          DATABASE_URL: postgres://svc_bcxfoms@kllsg-sgp-dv-foms-db-01:gx6,7ak3*zed@<ap@kllsg-sgp-dv-foms-db-01.privatelink.postgres.database.azure.com:5432/i12_cms
          PORT: 1338
          
          AWS_S3_KEY: akiawipttxol7hklhcpy
          AWS_S3_SECRET: axkhn1wqapzxlz3wxniasidxxnebfqbd+cxwzzd
          AWS_S3_REGION: ap-southeast-1
          AWS_S3_BUCKET: i12
          AWS_CLOUDFRONT: https://d392yifhajo78a.cloudfront.net/
          STRAPI_LICENSE: zk0zqlrnzkfrwdzi2ktgkkzd1xlvltnhsavgrb1pwfxhzvfqzgjzrgpud1lyzgtzvlvflder5yzgmpa3wmxayczszw1wy20xwjuzmelldheycm1ktw1rd0ltzrjbnvlncznpjc/ramfnyejtqn/xzftyrbgnwrmfbpxfhdwdnvy15ylouapra1kty7gnhyd55xkzaevprq

        run: |
          yarn install
          yarn run build 

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'i12katongweb-ut'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1EDB02F545C4CFB81E24AE76387CD57 }}
